version: "3.9"

networks:
  proxy:
    external: false
  immich_network:
    driver: bridge
  nextcloud_network:
    driver: bridge

volumes:
  npm_data:
  npm_letsencrypt:
  vaultwarden_data:
  nextcloud_data:
  nextcloud_pgdata:
  immich_pgdata:
  immich_uploads:

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - proxy
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "80"
      DOMAIN: "https://vault.drawde.cz"
    expose:
      - "80"
    networks:
      - proxy
    volumes:
      - vaultwarden_data:/data

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy
      - nextcloud_network
    environment:
      POSTGRES_HOST: nextcloud-postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloudpass
    volumes:
      - nextcloud_data:/var/www/html

  nextcloud-postgres:
    image: postgres:14
    container_name: nextcloud-postgres
    restart: unless-stopped
    networks:
      - nextcloud_network
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloudpass
      POSTGRES_DB: nextcloud
    volumes:
      - nextcloud_pgdata:/var/lib/postgresql/data

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    networks:
      - immich_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: immich
    volumes:
      - immich_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - immich_network

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    depends_on:
      - immich-postgres
      - immich-redis
    expose:
      - "3001"
    networks:
      - proxy
      - immich_network
    environment:
      DB_URL: postgresql://postgres:rootpass@immich-postgres:5432/immich
      REDIS_URL: redis://immich-redis:6379
      NODE_ENV: production
    volumes:
      - immich_uploads:/usr/src/app/upload

    syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    expose:
      - "8384"
      - "22000/tcp"
      - "22000/udp"
    networks:
      - proxy
    volumes:
      - /srv/syncthing:/var/syncthing
      - /srv/photos:/var/syncthing/Sync

