version: "3.9"

networks:
  proxy:
    external: false

volumes:
  npm_data:
  npm_letsencrypt:
  vaultwarden_data:
  nextcloud_data:
  immich_pgdata:
  immich_uploads:
  syncthing_config:

services:

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - proxy
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "80"
      DOMAIN: "https://vault.drawdekyluk.duckdns.org"
    expose:
      - "80"
    networks:
      - proxy
    volumes:
      - vaultwarden_data:/data

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy
    environment:
      POSTGRES_HOST: immich-postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloudpass
    volumes:
      - nextcloud_data:/var/www/html

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      - immich-postgres
      - immich-redis
    expose:
      - "3001"
    environment:
      DB_URL: postgresql://immich:immich@immich-postgres:5432/immich
      REDIS_URL: redis://immich-redis:6379
      NODE_ENV: production
    volumes:
      - immich_uploads:/usr/src/app/upload

  immich-redis:
    image: redis:7
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - proxy

  immich-postgres:
    image: postgres:14
    container_name: immich-postgres
    restart: unless-stopped
    networks:
      - proxy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: immich
    volumes:
      - immich_pgdata:/var/lib/postgresql/data
